plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.4.1'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.4.1'

    compileOnly project(":bootimage")

    compileOnly("dev.ultreon.mods:xinexlib-common-1.21.1:0.1.0-SNAPSHOT")
    compileOnly("org.graalvm.polyglot:polyglot:24.1.1")
    compileOnly("org.graalvm.python:python-community:24.1.1")
    compileOnlyApi("io.github.kawamuray.wasmtime:wasmtime-java:0.19.0")

    // Extra dependencies
    compileOnly "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdx_version", {
        exclude group: "org.lwjgl.lwjgl"
        exclude group: "org.lwjgl"
    }

    compileOnly 'com.github.Nuix:jnode-fs:v1.0.1', {
        exclude group: "com.google.guava"
    }
    compileOnly "com.badlogicgames.gdx:gdx:$gdx_version"
    compileOnly "com.badlogicgames.gdx:gdx-platform:$gdx_version:natives-desktop"
}

classes {
    doLast {
        copy {
            from(project(":bootimage").sourceSets.main.output)
            into(outputs)
        }
    }
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
repositories {
    mavenCentral()
}
